// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	group2 "go-zero-api/api/code/internal/handler/group2"
	ucenter "go-zero-api/api/code/internal/handler/ucenter"
	"go-zero-api/api/code/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Check},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/jsonParam",
					Handler: ucenter.JsonParamHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/formParamPost",
					Handler: ucenter.FormParamPostHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/formParamGet",
					Handler: ucenter.FormParamGetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/pathParam/:id/:name",
					Handler: ucenter.PathParamHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uploadFile",
					Handler: ucenter.UploadFileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/downloadFile",
					Handler: ucenter.DownloadFileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/previewFile",
					Handler: ucenter.PreviewFileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/ucenter"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: group2.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/group2"),
	)
}
